name: Test
on:
  push:
    branches:
    - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up CouchDB
      uses: ./
      with:
        couchdb version: '3'
        couchdb port: 3001
        couchdb user: workflow
        couchdb password: hallo
    - name: Test that CouchDB can be accessed
      run: curl -sS -f http://127.0.0.1:3001/
    - name: Test that system databases are there
      run: curl -sS -f http://127.0.0.1:3001/_users
    - name: lalala
      run: curl http://127.0.0.1:3001/_all_dbs
