name: Test
on:
  push:
    branches:
    - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up CouchDB
      uses: ./
    - name: Test that CouchDB can be accessed
      run: curl -sS -f http://127.0.0.1:3001/
    - name: See if that worked
      run: | 
        curl GET http://127.0.0.1:3001/_all_dbs
        curl -X POST -H "Content-Type: application/json" -d '{ "test": "test" }' http://127.0.0.1:3001/rtest
        curl -X GET http://127.0.0.1:3001/rtest/02932bc4-22ce-3080-a205-e050b489c0c2