name: Test
on:
  push:
    branches:
    - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up CouchDB
      uses: ./
      with:
        couchdb version: '2.3.1'
        couchdb port: 3001
    - name: Test that CouchDB can be accessed
      run: curl -sS -f http://127.0.0.1:3001/
    - name: Test that system databases are there
      run: curl -sS -f http://127.0.0.1:3001/_users
    - name: Set up CouchDB v4
      uses: ./
      with:
        couchdb version: '4'
    - name: Test that CouchDB can be accessed
      run: curl -sS -f http://127.0.0.1:5984/
    - name: Test that system databases are there
      run: curl -sS -f http://127.0.0.1:5984/_users
