name: Test
on:
  push:
    branches:
    - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up CouchDB
      uses: ./
      with:
        couchdb version: '2.3.1'
        couchdb port: 3001
    - name: Test that CouchDB can be accessed
      run: curl -sS -f http://127.0.0.1:3001/
    - name: Test that system databases are there
      run: curl -sS -f http://127.0.0.1:3001/_users
    - name: make db see if i can add stuff
      run: | 
        curl -X PUT http://127.0.0.1:3001/rtest
        curl -X POST -H "Content-Type: application/json" -d '{"identifier": "blablubb", "test": 30}' http://127.0.0.1:3001/rtest
